name: CMake compilation # NO NEED TO CHANGE HERE

on: [push] # NO NEED TO CHANGE HERE

env:
  BUILD_TYPE: Release # NO NEED TO CHANGE HERE

jobs:
  build:
    runs-on: ubuntu-20.04 # NO NEED TO CHANGE HERE

    steps:
    - uses: actions/checkout@v2 # NO NEED TO CHANGE HERE
    - name: Build CMake example # NO NEED TO CHANGE HERE
      # Choose the working directory
      working-directory: ${{github.workspace}}/PA1 # YOU NEED TO CHANGE THE FOLDER NAME TO YOUR OWN FOLDER NAME
      shell: bash

     #this is justin here do not mkdir a new build folder you already have one
      run: (cmake -B build -S .;cmake --build build) # NO NEED TO CHANGE HERE
